apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  labels:
    app: iperf3-server
spec:
  containers:
  - name: iperf3-server
    image: networkstatic/iperf3
    command: ["-s"]
    volumeMounts:
    - name: iperf3-data
      mountPath: /mnt/iperf3-data
    ports:
    - containerPort: 5201
  volumes:
  - name: iperf3-data
    emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: iperf3-server
spec:
  selector:
    app: iperf3-server
  ports:
  - protocol: TCP
    port: 5201
    targetPort: 5201
