apiVersion: v1
kind: Pod
metadata:
  name: iperf-overlay-client
  labels:
    app: iperf-overlay-client
spec:
  containers:
  - name: iperf-overlay-client
    image: jmarhee/iperf:latest
    command: ["iperf","-c", "iperf-overlay-server", "-t", "300","-i","300"]
    ports:
    - containerPort: 5001
---
kind: Service
apiVersion: v1
metadata:
  name: iperf-overlay-client
spec:
  selector:
    app: iperf-overlay-client
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
