---
- name: Ansible test
  hosts: [localhost]
  user: root
  vars:
    packages: [qemu-kvm,libvirt-bin,ubuntu-vm-builder,bridge-utils,openvswitch-switch,libxml2-dev,libxslt-dev,python-dev,python3-lxml]

  tasks:
    - name: install packages
      apt-get:
        name: "{{ packages }}"
        state: present

  # Create a bridge named br-int
    - openvswitch_bridge:
        bridge: yjkamdar-netl3
        state: present

    - name: Install VM1
      become: yes
      command: virt-clone --original sampleVM -n yjkamdarVM1 --auto-clone
      ignore_errors: yes

    - name: Install VM2
      become: yes
      command: virt-clone --original sampleVM -n yjkamdarVM2 --auto-clone
      ignore_errors: yes

    - name: Start VM1
      virt:
        name: yjkamdarVM1
        command: start
        state: running

    - name: Start VM2
      virt:
        name: yjkamdarVM2
        command: start
        state: running

    - virt_net:
      command: list_nets
      #sudo virt-clone --original VM2 -n VM3 --auto-clone
      # - name: Create VM2 from VM1
      #become: yes
      #command: sudo virt-clone --original yjkamdarVM1 -n yjkamdarVM2 --auto-clone 
