---
- name: Get Load averages playbook
  hosts: [hosts]
  user: root
  vars_files:
    - vars/config.yml
  vars:
    - LOG_PATH: /var/customlogs/logs
    - SCRIPT_PATH: /var/customlogs/scripts
  tasks:
    - ping:

    - name: Ensures {{LOG_PATH}} dir exists
      file: path={{LOG_PATH}} state=directory

    - name: Ensures {{SCRIPT_PATH}} dir exists
      file: path={{SCRIPT_PATH}} state=directory

    - name: Clear previous logs
      command: "rm -f {{ LOG_PATH }}/load.csv {{ LOG_PATH }}/load_alerts.csv"

    - name: Copy load average script
      template: 
        src: scripts/log_loads.sh.j2
        dest: "{{ SCRIPT_PATH }}/log_loads.sh"

    - name: Store curr load average
      command: "sh {{ SCRIPT_PATH }}/log_loads.sh {{ TP }}"
