packages: [qemu-kvm,libvirt-bin,ubuntu-vm-builder,bridge-utils,openvswitch-switch,libxml2-dev,libxslt-dev,python-dev,python-lxml,dnsmasq]

ovs_networks:
  - name: Internet-yk
    type: internet
    mode: nat
    br_name: sw1-yk
    range: 10.10.10.2,10.10.10.254
    ip: 10.10.10.1/24
  - name: L2-yk
    type: l2
    mode: bridge
    br_name: sw2-yk
  - name: L3-yk
    type: l3
    mode: routed
    br_name: sw3-yk
    range: 10.10.11.2,10.10.11.254
    ip: 10.10.11.1/24
  - name: Other-yk
    type: other
    mode: routed
    br_name: sw4-yk
    range: 10.10.12.2,10.10.12.254
    ip: 10.10.12.1/24