apiVersion: v1
kind: Pod
metadata:
  name: iperf-overlay-server
  labels:
    app: iperf-overlay-server
spec:
  containers:
  - name: iperf-overlay-server
    image: jmarhee/iperf:latest
    command: ["iperf","-s","-u"]
    volumeMounts:
    - name: iperf-data
      mountPath: /mnt/iperf-data
    ports:
    - containerPort: 5001
  volumes:
  - name: iperf-data
    emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: iperf-overlay-server
spec:
  selector:
    app: iperf-overlay-server
  ports:
  - protocol: UDP
    port: 5001
    targetPort: 5001
