---
- name: Ansible delete Infra playbook
  hosts: [localhost]
  user: root
  vars_files:
    - vars/config.yml
    
  tasks:
    - name: install packages
      apt:
        name: "{{ packages }}"
        state: present

# VM configuration: creating, starting and attaching interfaces
    - name: Shutdown all VMs
      virt:
        name: "{{ item.name }}"
        command: shutdown
        state: shutdown
      ignore_errors: true
      loop: "{{ VMs }}"        

# Define the network in bridge mode and start the ovs network infra
    - name: Stop OVS network
      virt_net:
        command: stop
        name: "{{ item.name }}"
        state: inactive
      become: yes
      ignore_errors: true
      loop: "{{ ovs_networks }}"
    - name: Undefine OVS network
      virt_net:
        command: undefine
        state: absent
        name: "{{ item.name }}"
        xml: '{{ lookup("template", "network/bridge-ovs.xml") }}'
      become: yes
      ignore_errors: true
      loop: "{{ ovs_networks }}"

#Configure NAT for networks with mode=nat
    - name: Remove NAT rule network iptables
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: "{{ item.br_name }}"
        source: '{{ item.ip }}'
        jump: MASQUERADE
        protocol: icmp
        state: absent
        comment: NAT network enable MASQUERADE
      loop: "{{ ovs_networks }}"
      when: item.mode=="nat"
      ignore_errors: true
      become: yes

    - name: Undefine all VMs
      virt:
        name: "{{ item.name }}"
        command: undefine
      ignore_errors: true
      loop: "{{ VMs }}"

# Create the required ovs bridges
    - name: Delete an OVS bridge
      openvswitch_bridge:
        bridge: "{{ item.br_name }}"
        state: absent
      become: yes
      ignore_errors: true
      loop: "{{ ovs_networks }}"
    